version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "my-task"  # Placeholder for task definition
        LoadBalancerInfo:
          ContainerName: "node"
          ContainerPort: 8080
