version: 0.2
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "PLACEHOLDER_TASK_DEFINITION"  # Placeholder for task definition
        LoadBalancerInfo:
          ContainerName: "nodeapp-container"
          ContainerPort: 8080
