version: 0.2
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:905418104867:task-definition/task-definition:4"  # Placeholder for task definition
        LoadBalancerInfo:
          ContainerName: "node"
          ContainerPort: 8080
