version: 0.2
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:905418104867:task-definition/my-task:14"  # Placeholder for task definition
        LoadBalancerInfo:
          ContainerName: "nodeapp-container"
          ContainerPort: 8080
